# Project's general Python settings

# ### ISORT config
[tool.isort]
profile            = "black"
combine_as_imports = true
default_section    = "THIRDPARTY"
sections           = [
  "FUTURE",
  "STDLIB",
  "THIRDPARTY",
  "FIRSTPARTY",
  "LOCALFOLDER"
]
import_heading_stdlib      = "Python imports"
import_heading_thirdparty  = "external imports"
import_heading_firstparty  = "app imports"
import_heading_localfolder = "local imports"
known_first_party          = "test_suite"


[tool.mypy]
python_version = "3.9"
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
show_error_codes = true
warn_unused_ignores = true
warn_unused_configs = true
