#!/usr/bin/env bash

# Actually overwrite whatever there was in the DHCP response!
echo "# FORCE devnet's nameserver" > /etc/resolv.conf
echo "nameserver fd21:9e0:de85:51e6:ffff:7e57:c0de:2" >> /etc/resolv.conf
